package com.ic_edita.instapay

import android.graphics.Color
import android.os.Bundle
import android.text.InputType
import android.view.Gravity
import android.view.View
import android.widget.LinearLayout
import android.widget.TextView
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.lifecycleScope
import androidx.room.Room
import com.google.android.material.bottomsheet.BottomSheetDialog
import com.google.android.material.button.MaterialButton
import com.google.android.material.dialog.MaterialAlertDialogBuilder
import com.google.android.material.textfield.TextInputEditText
import com.ic_edita.instapay.databinding.ActivitySettingsBinding
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

class SettingsActivity : AppCompatActivity() {
    private lateinit var binding: ActivitySettingsBinding
    private lateinit var store: AzureSettingsStore
    private val database by lazy { Room.databaseBuilder(applicationContext, AppDatabase::class.java, "instapay.db").build() }
    private val importNotesFile = registerForActivityResult(ActivityResultContracts.OpenDocument()) { uri -> uri ?: return@registerForActivityResult; lifecycleScope.launch(Dispatchers.IO) { try { val result=ApprovedNotesExcelImporter(this@SettingsActivity).import(uri); withContext(Dispatchers.Main){ confirmImport(result) } } catch(error:Exception) { withContext(Dispatchers.Main){ showMessage("Import failed", error.message ?: "The Excel file could not be read.") } } } }

    override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState); binding=ActivitySettingsBinding.inflate(layoutInflater); setContentView(binding.root); store=AzureSettingsStore(this); binding.endpointInput.setText(store.endpoint()); binding.keyInput.setText(store.apiKey()); binding.settingsToolbar.setNavigationOnClickListener { finish() }; binding.saveSettingsButton.setOnClickListener { save() }; binding.testButton.setOnClickListener { save(); binding.settingsStatus.text="Settings saved. Select a receipt on Home and choose Extract data to test OCR." }; binding.approvedAccountsButton.setOnClickListener { requestPassword("accounts") }; binding.approvedNotesButton.setOnClickListener { requestPassword("notes") } }
    private fun save(){ val endpoint=binding.endpointInput.text?.toString().orEmpty().trim().trimEnd('/'); val key=binding.keyInput.text?.toString().orEmpty().trim(); if(!endpoint.startsWith("https://")){ binding.endpointLayout.error="Use an https:// Azure endpoint"; return }; if(key.isBlank()){ binding.keyLayout.error="Subscription key is required"; return }; binding.endpointLayout.error=null; binding.keyLayout.error=null; store.save(endpoint,key); binding.settingsStatus.text="Azure OCR settings saved securely on this device." }
    private fun requestPassword(section:String){ val input=TextInputEditText(this).apply { hint="Password"; inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_VARIATION_PASSWORD; isSingleLine=true }; val box=LinearLayout(this).apply { orientation=LinearLayout.VERTICAL; setPadding(48,0,48,0); addView(input) }; MaterialAlertDialogBuilder(this).setTitle("Protected settings").setMessage("Enter the administrator password to manage approved values.").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Continue",null).create().also { dialog -> dialog.setOnShowListener { dialog.getButton(android.app.AlertDialog.BUTTON_POSITIVE).setOnClickListener { if(store.isApprovedAccountsPasswordValid(input.text?.toString().orEmpty())) { dialog.dismiss(); if(section=="accounts") showApprovedAccountsSheet() else showApprovedNotesSheet() } else input.error="Incorrect password" } }; dialog.show() } }
    private fun showApprovedAccountsSheet(){ val sheet=BottomSheetDialog(this); val root=LinearLayout(this).apply { orientation=LinearLayout.VERTICAL; setPadding(32,24,32,32) }; val title=TextView(this).apply { text="Approved account numbers"; textSize=20f; setTextColor(Color.BLACK); setPadding(0,0,0,16) }; val list=LinearLayout(this).apply { orientation=LinearLayout.VERTICAL }; val selected=arrayOfNulls<ApprovedAccount>(1); val empty=TextView(this).apply { text="No approved account numbers yet."; gravity=Gravity.CENTER; visibility=View.GONE; setPadding(0,24,0,24) }; val add=MaterialButton(this).apply { text="Add account number" }; val remove=MaterialButton(this).apply { text="Remove selected number"; isEnabled=false }; root.addView(title); root.addView(list); root.addView(empty); root.addView(add); root.addView(remove); sheet.setContentView(root); fun refresh(){ lifecycleScope.launch { val accounts=withContext(Dispatchers.IO){ database.admin().accounts() }; list.removeAllViews(); empty.visibility=if(accounts.isEmpty()) View.VISIBLE else View.GONE; accounts.forEach { account -> val row=TextView(this@SettingsActivity).apply { text=account.accountNumber; textSize=17f; setPadding(20,18,20,18); setOnClickListener { selected[0]=account; remove.isEnabled=true; list.children().forEach { it.isSelected=false }; isSelected=true } }; list.addView(row) } } }; add.setOnClickListener { promptAddAccount { refresh() } }; remove.setOnClickListener { selected[0]?.let { account -> lifecycleScope.launch(Dispatchers.IO){ database.admin().removeAccount(account); withContext(Dispatchers.Main){ selected[0]=null; remove.isEnabled=false; refresh() } } } }; refresh(); sheet.show() }
    private fun showApprovedNotesSheet(){ val sheet=BottomSheetDialog(this); val root=LinearLayout(this).apply { orientation=LinearLayout.VERTICAL; setPadding(32,24,32,32) }; val title=TextView(this).apply { text="Approved Note numbers"; textSize=20f; setTextColor(Color.BLACK); setPadding(0,0,0,16) }; val list=LinearLayout(this).apply { orientation=LinearLayout.VERTICAL }; val selected=arrayOfNulls<ApprovedNote>(1); val empty=TextView(this).apply { text="No approved Note numbers yet."; gravity=Gravity.CENTER; visibility=View.GONE; setPadding(0,24,0,24) }; val import=MaterialButton(this).apply { text="Import Excel file" }; val add=MaterialButton(this).apply { text="Add Note number" }; val remove=MaterialButton(this).apply { text="Remove selected number"; isEnabled=false }; root.addView(title); root.addView(list); root.addView(empty); root.addView(import); root.addView(add); root.addView(remove); sheet.setContentView(root); fun refresh(){ lifecycleScope.launch { val notes=withContext(Dispatchers.IO){ database.admin().notes() }; list.removeAllViews(); empty.visibility=if(notes.isEmpty()) View.VISIBLE else View.GONE; notes.forEach { note -> val row=TextView(this@SettingsActivity).apply { text=if(note.name.isBlank()) note.noteNumber else "${note.noteNumber} — ${note.name}"; textSize=17f; setPadding(20,18,20,18); setOnClickListener { selected[0]=note; remove.isEnabled=true; list.children().forEach { it.isSelected=false }; isSelected=true } }; list.addView(row) } } }; import.setOnClickListener { importNotesFile.launch(arrayOf("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/vnd.ms-excel")) }; add.setOnClickListener { promptAddNote { refresh() } }; remove.setOnClickListener { selected[0]?.let { note -> lifecycleScope.launch(Dispatchers.IO){ database.admin().removeNote(note); withContext(Dispatchers.Main){ selected[0]=null; remove.isEnabled=false; refresh() } } } }; refresh(); sheet.show() }
    private fun confirmImport(result:ApprovedNotesImportResult){ val message="Rows inspected: ${result.rowsInspected}\nValid Note numbers: ${result.validNotes.size}\nDuplicates ignored: ${result.duplicateCount}\nInvalid rows skipped: ${result.invalidRowCount}"; MaterialAlertDialogBuilder(this).setTitle("Confirm Note-number import").setMessage(message).setNegativeButton("Cancel",null).setPositiveButton("Import") { _,_ -> lifecycleScope.launch(Dispatchers.IO){ database.admin().addNotes(result.validNotes); withContext(Dispatchers.Main){ showMessage("Import complete", "${result.validNotes.size} approved Note numbers were merged into the local list.") } } }.show() }
    private fun promptAddNote(onAdded:()->Unit){ val input=TextInputEditText(this).apply { hint="Note number"; inputType=InputType.TYPE_CLASS_NUMBER; isSingleLine=true }; val box=LinearLayout(this).apply { orientation=LinearLayout.VERTICAL; setPadding(48,0,48,0); addView(input) }; MaterialAlertDialogBuilder(this).setTitle("Add approved Note number").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Add") { _,_ -> val value=input.text?.toString().orEmpty().trim(); if(value.isNotBlank()) lifecycleScope.launch(Dispatchers.IO){ database.admin().addNote(ApprovedNote(value)); withContext(Dispatchers.Main){ onAdded() } } }.show() }
    private fun promptAddAccount(onAdded:()->Unit){ val input=TextInputEditText(this).apply { hint="Account number or @instapay handle"; isSingleLine=true }; val box=LinearLayout(this).apply { orientation=LinearLayout.VERTICAL; setPadding(48,0,48,0); addView(input) }; MaterialAlertDialogBuilder(this).setTitle("Add approved account").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Add") { _,_ -> val value=input.text?.toString().orEmpty().trim(); if(value.isNotBlank()) lifecycleScope.launch(Dispatchers.IO){ database.admin().addAccount(ApprovedAccount(value)); withContext(Dispatchers.Main){ onAdded() } } }.show() }
    private fun showMessage(title:String, message:String){ MaterialAlertDialogBuilder(this).setTitle(title).setMessage(message).setPositiveButton("OK",null).show() }
}
private fun LinearLayout.children():List<View>=(0 until childCount).map{getChildAt(it)}
